import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["src/**/*.test.ts"],
    exclude: ["src/**/*.integration.test.ts"],
    coverage: {
      provider: "v8",
      include: [
        "src/architecture/module-boundaries.ts",
        "src/architecture/official-resource-integrity.ts",
        "src/modules/builder/domain/ecf31-core-draft.ts",
        "src/modules/builder/domain/ecf31-detalles-items-evidence.ts",
        "src/modules/builder/domain/ecf31-item-code-metadata-evidence.ts",
        "src/modules/builder/domain/ecf31-item-description-metadata-evidence.ts",
        "src/modules/builder/domain/ecf31-item-unit-metadata-evidence.ts",
        "src/modules/builder/domain/ecf31-item-dates-metadata-evidence.ts",
        "src/modules/builder/domain/ecf31-core-header.ts",
        "src/modules/builder/domain/ecf31-iddoc-issuance-evidence.ts",
        "src/modules/builder/infrastructure/ecf31-iddoc-xml-mapper.ts",
        "src/modules/builder/infrastructure/ecf31-totales-xml-mapper.ts",
        "src/modules/builder/infrastructure/ecf31-detalles-items-xml-mapper.ts",
        "src/modules/builder/infrastructure/ecf31-encabezado-xml-mapper.ts",
        "src/modules/builder/infrastructure/ecf31-xml-assembler.ts",
        "src/modules/builder/infrastructure/offline-dgii-xsd-validator.ts",
        "src/modules/builder/application/ecf31-core-header-snapshot-codec.ts",
        "src/modules/builder/application/ecf31-core-line-snapshot-codec.ts",
        "src/modules/builder/application/ecf31-line-adjustment-snapshot-codec.ts",
        "src/modules/builder/application/ecf31-header-totals-snapshot-codec.ts",
        "src/modules/builder/application/ecf31-persistable-draft-evidence-snapshot-codec.ts",
        "src/modules/draft-persistence/infrastructure/postgres-ecf31-draft-evidence-repository.ts",
        "src/modules/builder/domain/ecf31-header-totals-evidence.ts",
        "src/modules/builder/domain/ecf31-derived-header-totals-evidence.ts",
        "src/modules/builder/domain/ecf31-core-line.ts",
        "src/modules/builder/domain/ecf31-line-amount-evidence.ts",
        "src/modules/builder/domain/ecf31-monto-item-quantization-evidence.ts",
        "src/modules/builder/domain/ecf31-itbis-price-inclusion-evidence.ts",
        "src/modules/builder/domain/ecf31-post-global-adjustment-taxable-base-evidence.ts",
        "src/modules/builder/domain/ecf31-total-itbis-evidence.ts",
        "src/modules/builder/domain/ecf31-post-global-adjustment-exempt-amount-evidence.ts",
        "src/modules/builder/domain/ecf31-monto-item-tolerance-gate-evidence.ts",
        "src/modules/builder/domain/ecf31-global-adjustment-initial-evidence.ts",
        "src/modules/builder/domain/ecf31-global-adjustment-reconciliation.ts",
        "src/modules/builder/domain/exact-decimal.ts",
        "src/modules/builder/domain/line-calculation-evidence.ts",
        "src/modules/fiscal-identity/domain/e-ncf.ts",
        "src/modules/fiscal-identity/domain/taxpayer-identifier.ts",
        "src/modules/certificate/infrastructure/in-memory-pkcs12-loader.ts",
        "src/modules/http-transport/infrastructure/dgii-http-transport.ts",
        "src/modules/dgii-auth/infrastructure/dgii-authentication.ts",
        "src/modules/dgii-reception/infrastructure/dgii-reception.ts",
        "src/modules/issuance/application/prepare-ecf31-delivery.ts",
        "src/modules/dgii-result-consultation/infrastructure/dgii-result-consultation.ts",
        "src/modules/dgii-result-consultation/infrastructure/dgii-result-polling-scheduler.ts",
        "src/modules/delivery-persistence/infrastructure/postgres-delivery-persistence.ts",
        "src/modules/backend-authorization/backend-scope-authority.ts",
        "src/internal/testecf-auth-smoke-core.ts",
        "src/internal/testecf-auth-smoke-native-adapter.ts",
        "src/internal/testecf-auth-smoke-worker.ts",
        "src/internal/testecf-auth-smoke-worker-main.ts",
        "src/internal/testecf-ecf31-probe-diagnostics.ts",
      ],
      reporter: ["text", "json", "html"],
      thresholds: {
        lines: 100,
        functions: 100,
        statements: 100,
        branches: 100,
      },
    },
  },
});
